services:
  dbhost:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: hop
      POSTGRES_PASSWORD: hop
      POSTGRES_DB: hop
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  python:
    build: python
    volumes:
      - ./data:/data
    environment:
      DATA_PATH: /data/hop_public_reviews.json

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: hop
      MB_DB_PASS: hop
      MB_DB_HOST: dbhost

volumes:
  postgres:
  metabase: